[package]
name = "onion-vm"
version = "0.1.0"
edition = "2021"

[lib]
name = "onion_vm"
crate-type = ["lib"]

[dependencies]
bincode = "1.3.3"
rust-arc-gc = "0.1.0"
rustc-hash = "2.1.1"
serde = { version = "1.0.219", features = ["derive"] }
