[package]
name = "onion-vm"
version = "0.1.0"
edition = "2021"

[lib]
name = "onion_vm"
crate-type = ["lib"]

[dependencies]
rust-arc-gc = "0.1.0"
serde = { version = "1.0.219", features = ["derive"] }
